# Generated by Django 4.2.5 on 2023-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='This', max_length=512, verbose_name='описание'),
        ),
    ]
